sudo: required
dist: trusty
addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
    - libssl-dev
    - libpcre3-dev
    - asciidoc
    - xmlto
before_install:
- git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git
script:
- cd shadowsocksr-libev
- ./configure --disable-documentation && make
# - sudo make install
# - sudo find / -name ss-local
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - src/ss-local
  skip_cleanup: true
  on:
    repo: erguotou520/ssr-libev-ci
    branch: master
