sudo: required
dist: trusty
addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
    - libssl-dev
    - libpcre3-dev
    - asciidoc
    - xmlto
before_install:
- git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git
script:
- cd shadowsocksr-libev
- ./configure && make
- sudo make install
# - sudo find / -name ss-local
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: completions/bash/*
  skip_cleanup: true