osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++
    compiler: clang
addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
    - libssl-dev
    - libpcre3-dev
    - asciidoc
    - xmlto
before_install:
- git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git
script:
- cd shadowsocksr-libev
- ./configure --disable-documentation && make
- sudo make install
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - src/ss-local
    - src/ss-redir
  skip_cleanup: true
  on:
    repo: erguotou520/ssr-libev-ci
    branch: master
