osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  # - os: osx
  - os: linux
    compiler: clang
addons:
  apt:
    packages:
    - build-essential
    - libz-dev
    - autoconf
    - libtool
    - libssl-dev
    - libpcre3-dev
    - xmlto
before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export OBJC=clang;
    export CC=clang;
    export OBJCXX=clang++;
    export CXX=clang++;
    export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig;
    export PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12;
    export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS";
    export LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS";
  fi'
- git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git
script:
- cd shadowsocksr-libev
- ./configure --disable-documentation --enable-static && make
- sudo -i which clang #https://github.com/travis-ci/travis-ci/issues/2607
- sudo make install
- mkdir -p /tmp/ssr
- cp src/ss-local /tmp/ssr
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    install_name_tool -change /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib @executable_path/libcrypto.1.0.0.dylib src/ss-local;
    install_name_tool -change /usr/local/opt/pcre/lib/libpcre.1.dylib @executable_path/libpcre.1.dylib src/ss-local;
    cp /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /tmp/ssr;
    cp /usr/local/opt/pcre/lib/libpcre.1.dylib /tmp/ssr;
  fi'
after_success:
  - cd /tmp/ssr
  - git init
  - git add ./ -A
  - git commit -m "Auto build with Travis CI"
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git push -u https://$GITHUB_TOKEN@github.com/erguotou520/ssr-libev-ci.git HEAD:darwin --force; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git push -u https://$GITHUB_TOKEN@github.com/erguotou520/ssr-libev-ci.git HEAD:linux --force; fi'
if: tag IS present
