osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++
    compiler: clang
addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
    - libssl-dev
    - libpcre3-dev
    - xmlto
before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'
- git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git
script:
- cd shadowsocksr-libev
- ./configure --disable-documentation --enable-static && make
- sudo -i which clang #https://github.com/travis-ci/travis-ci/issues/2607
- sudo make install
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - src/ss-local
    - src/ss-redir
  skip_cleanup: true
  on:
    repo: erguotou520/ssr-libev-ci
    branch: master
branches:
  only:
  - master
