osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  # - os: osx
  - os: linux
    compiler: clang
addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
    - libssl-dev
    - libpcre3-dev
    - xmlto
    - mingw-w64
before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'
- git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git
script:
- cd shadowsocksr-libev
- ./configure --disable-documentation --enable-static && make
- sudo -i which clang #https://github.com/travis-ci/travis-ci/issues/2607
- sudo make install
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    cd ../;
    curl -O https://www.openssl.org/source/openssl-1.0.2o.tar.gz;
    tar zxf openssl-1.0.2o.tar.gz;
    cd openssl-1.0.2o;
    CROSS_COMPILE="x86_64-w64-mingw32-" ./Configure mingw64 no-asm shared --prefix=$HOME/prebuilt --openssldir=$HOME/prebuilt/openssl;
    make && make install;
    cd ../shadowsocksr-libev;
    ./configure --host=x86_64-w64-mingw32 --disable-documentation --enable-static;
    make && make install;
  fi'
before_deploy:
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv src/ss-local src/ss-local_darwin; fi'
- 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv src/ss-local src/ss-local_linux; fi'
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - src/ss-local_darwin
    - src/ss-local_linux
    - bin/ss-local.exe
  skip_cleanup: true
  on:
    repo: erguotou520/ssr-libev-ci
    branch: master
    tags: true
# if: tag IS present
