version: 0.1.{build}
branches:
  only:
    - master
image: Visual Studio 2017
platform:
  - x32
environment:
  global:
    ROOT_PATH: C:\MinGW
    BIN_PATH: C:\MinGW\bin

max_jobs: 1

init:
  - git config --global core.autocrlf input
  - curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -


build_script:
  # - cmd: '%BIN_PATH\bash --login -lc'
# after_build:
#   - cmd: DIR C:\cygwin\home

test: off
# deploy:
  # release: myproduct-v$(appveyor_build_version)
  # description: 'Release description'
  # provider: GitHub
  # auth_token:
    # secure: xIE5SqqZsm2W0Df0iY3ixz/silVwIQy++z049I6SepBdzqlGSnBjXOac3d987ST5 # your encrypted token from GitHub
  # artifact: 'C:\cygwin\home\appveyor\shadowsocksr-libev\src\ss-local.exe' # upload ss-local.exe to release assets
  # on:
    # branch: master                 # release from master branch only
    # appveyor_repo_tag: true        # deploy on tag push only
  # force_update: true
