version: 0.1.{build}
branches:
  only:
    - master
image: Visual Studio 2017
platform:
  - x32
environment:
    global:
        CYG_ROOT: C:\cygwin

max_jobs: 1

init:
  - git config --global core.autocrlf input

# curl -O https://www.openssl.org/source/openssl-1.0.2o.tar.gz;
# tar zxf openssl-1.0.2o.tar.gz;
# cd openssl-1.0.2o;
# ./config --prefix=\"$HOME/prebuilt\" --openssldir=\"$HOME/prebuilt/openssl\";
# make && make install;

# C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl
# c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages automake,gcc-g++,make,pkg-config,openssl-devel,libicu-devel,zlib-devel,libcrypt-devel,perl,python3-devel,libsasl2-devel,cygport

build_script:
  - cmd: '%CYG_ROOT%\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P autoconf -P automake -P bison -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl -P openssl-devel -P zlib-devel -P cygport -P libpcre-devel -P libcrypt-devel'
  - cmd: 'mkdir %APPVEYOR_BUILD_FOLDER%\install'
  - cmd: '%CYG_ROOT%/bin/bash --login -lc "export CYGWIN=winsymlinks:native;
    mount \"$APPVEYOR_BUILD_FOLDER\install\" /usr/local;
    cd $APPVEYOR_BUILD_FOLDER;
    git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git;
    cd shadowsocksr-libev;
    ./configure --prefix="$HOME/ss" --with-openssl="$HOME/prebuilt" --disable-documentation --enable-static;
    make && make install;
    curl -o- -L https://gist.githubusercontent.com/stefanbuck/ce788fee19ab6eb0b4447a85fc99f447/raw/dbadd7d310ce8446de89c4ffdf1db0b400d0f6c3/upload-github-release-asset.sh| bash -s -- github_api_token=$GITHUB_TOKEN owner=erguotou520 repo=ssr-libev-ci tag=0.0.1 filename=src/ss-local.exe;
    umount /usr/local"'
after_build:
  - cmd: DIR C:\cygwin\

test: off
# deploy:
  # release: myproduct-v$(appveyor_build_version)
  # description: 'Release description'
  # provider: GitHub
  # auth_token:
    # secure: xIE5SqqZsm2W0Df0iY3ixz/silVwIQy++z049I6SepBdzqlGSnBjXOac3d987ST5 # your encrypted token from GitHub
  # artifact: 'C:\cygwin\home\appveyor\shadowsocksr-libev\src\ss-local.exe' # upload ss-local.exe to release assets
  # on:
    # branch: master                 # release from master branch only
    # appveyor_repo_tag: true        # deploy on tag push only
  # force_update: true
