version: 0.1.{build}
branches:
  only:
    - master
# skip_non_tags: true
only_commits:
  message: /^trigger ci:/
image: Visual Studio 2015
platform:
  - x32
max_jobs: 1

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - ps: set MSYSTEM=MINGW64
  - ps: git config --global core.autocrlf input
  - ps: git config --global push.default matching
  - ps: git config --global user.name "erguotou"
  - ps: git config --global user.email "erguotou525@gmail.com"
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/erguotou520/ssr-libev-ci/master/msys.sh' -FileName C:\msys64\home\appveyor\msys.sh
  #  生成home目录
  - ps: C:\msys64\usr\bin\bash.exe --login -c "pwd && pacman -Syu --noconfirm"
build_script:
  - ps: set MSYSTEM=MINGW64
  - ps: C:\msys64\usr\bin\bash.exe --login -c "chmod +x msys.sh && ./msys.sh"
after_build:
  - ps: mkdir ssr
  - ps: Copy-Item C:\msys64\home\appveyor\shadowsocksr-libev\src\ss-local.exe C:\Users\appveyor\ssr
  - ps: Copy-Item C:\msys64\mingw64\bin\libeay32.dll C:\Users\appveyor\ssr
  - ps: Copy-Item C:\msys64\mingw64\bin\libpcre-1.dll C:\Users\appveyor\ssr
  - ps: Copy-Item C:\msys64\mingw64\bin\libssp-0.dll C:\Users\appveyor\ssr
  - ps: Copy-Item C:\msys64\mingw64\bin\libwinpthread-1.dll C:\Users\appveyor\ssr
  - ps: cd ssr
  - ps: git init
  - ps: git add ./ -A
  - ps: git commit -m "Auto build with Appveyor"
  - ps: git push -u https://$GITHUB_TOKEN@github.com/erguotou520/ssr-libev-ci.git HEAD:win32 --force
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
test: off
