version: 0.1.{build}
branches:
  only:
    - master
image: Visual Studio 2015
platform:
  - x32
environment:
  ROOT_PATH: C:\MinGW
  BIN_PATH: C:\MinGW\bin
  MSYS_PATH: C:\MinGW\msys\1.0
  SHELL_PATH: C:\MinGW\msys\1.0\bin\sh.exe

max_jobs: 1

init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
  - cmd: 'C:\MinGW\bin\mingw-get.exe install mingw32-libz'
  - cmd: 'C:\MinGW\bin\mingw-get.exe install mingw32-pthreads-w32'
  - cmd: 'C:\MinGW\msys\1.0\bin\sh.exe --login -c "pwd"'
  - ps: Start-FileDownload 'https://www.openssl.org/source/openssl-1.0.2o.tar.gz' -FileName C:\MinGW\msys\1.0\home\appveyor\openssl-1.0.2o.tar.gz
  - ps: Start-FileDownload 'https://ftp.pcre.org/pub/pcre/pcre-8.42.zip' -FileName C:\MinGW\msys\1.0\home\appveyor\pcre-8.42.zip
  - ps: Start-FileDownload 'https://raw.githubusercontent.com/erguotou520/ssr-libev-ci/master/build.sh' -FileName C:\MinGW\msys\1.0\home\appveyor\build.sh
  - cmd: 'C:\MinGW\msys\1.0\bin\sh.exe --login -c "tar zxf openssl-1.0.2o.tar.gz"'
  - cmd: '7z x C:\MinGW\msys\1.0\home\appveyor\pcre-8.42.zip -o"C:\MinGW\msys\1.0\home\appveyor"'
  - cmd: 'git clone https://github.com/shadowsocksr-backup/shadowsocksr-libev.git C:\MinGW\msys\1.0\home\appveyor\shadowsocksr-libev'
build_script:
  - cmd: 'C:\MinGW\msys\1.0\bin\sh.exe --login -c "chmod +x build.sh&&./build.sh"'
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
test: off
